package resolver;

public enum SampleData {
	PRODUCTS_JSON("[\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000416566\",\n"
		+ "        \"prdlst_nm\": \"수면엔 테라슬립 락티움 제트 솔루션 ZZZ\",\n"
		+ "        \"prms_dt\": \"20221014\",\n"
		+ "        \"prdlst_report_no\": \"200400200082583\",\n"
		+ "        \"bssh_nm\": \"주식회사 노바렉스\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"1\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000416230\",\n"
		+ "        \"prdlst_nm\": \"메디폴리스(Medipolis)\",\n"
		+ "        \"prms_dt\": \"20221014\",\n"
		+ "        \"prdlst_report_no\": \"2015001201354\",\n"
		+ "        \"bssh_nm\": \"유니크바이오텍(주)\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"2\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000416989\",\n"
		+ "        \"prdlst_nm\": \"Aqua snow white rose(전량수출용)\",\n"
		+ "        \"prms_dt\": \"20221014\",\n"
		+ "        \"prdlst_report_no\": \"200400200023261\",\n"
		+ "        \"bssh_nm\": \"코스맥스바이오(주)\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"3\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000416998\",\n"
		+ "        \"prdlst_nm\": \"기억력 업 플러스(Memory Up Plus)\",\n"
		+ "        \"prms_dt\": \"20221014\",\n"
		+ "        \"prdlst_report_no\": \"2020001605265\",\n"
		+ "        \"bssh_nm\": \"주식회사 상상바이오\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"4\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000417000\",\n"
		+ "        \"prdlst_nm\": \"닥터에스더 어린콜라겐 비오틴 플러스\",\n"
		+ "        \"prms_dt\": \"20221014\",\n"
		+ "        \"prdlst_report_no\": \"202000162024\",\n"
		+ "        \"bssh_nm\": \"주식회사 바이오360\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"5\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000416999\",\n"
		+ "        \"prdlst_nm\": \"더힘찬 면역 홍삼정 23\",\n"
		+ "        \"prms_dt\": \"20221014\",\n"
		+ "        \"prdlst_report_no\": \"20040020031430\",\n"
		+ "        \"bssh_nm\": \"대동고려삼(주)\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"6\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000417191\",\n"
		+ "        \"prdlst_nm\": \"맥스(MAX) 4,200\",\n"
		+ "        \"prms_dt\": \"20221014\",\n"
		+ "        \"prdlst_report_no\": \"200400200201066\",\n"
		+ "        \"bssh_nm\": \"엠에스바이오텍(주)\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"7\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000416997\",\n"
		+ "        \"prdlst_nm\": \"부광마그빈\",\n"
		+ "        \"prms_dt\": \"20221014\",\n"
		+ "        \"prdlst_report_no\": \"200400200023263\",\n"
		+ "        \"bssh_nm\": \"코스맥스바이오(주)\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"8\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000417189\",\n"
		+ "        \"prdlst_nm\": \"데일리와이케어 유산균\",\n"
		+ "        \"prms_dt\": \"20221014\",\n"
		+ "        \"prdlst_report_no\": \"200400200201065\",\n"
		+ "        \"bssh_nm\": \"엠에스바이오텍(주)\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"9\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000416992\",\n"
		+ "        \"prdlst_nm\": \"슈프리다이어트프로바이오틱스(SUPRE DIET PROBIOTICS)\",\n"
		+ "        \"prms_dt\": \"20221014\",\n"
		+ "        \"prdlst_report_no\": \"200400200201064\",\n"
		+ "        \"bssh_nm\": \"엠에스바이오텍(주)\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"10\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000416990\",\n"
		+ "        \"prdlst_nm\": \"슈프리베베프로바이오틱스(SUPRE BEBE PROBIOTICS)\",\n"
		+ "        \"prms_dt\": \"20221014\",\n"
		+ "        \"prdlst_report_no\": \"200400200201062\",\n"
		+ "        \"bssh_nm\": \"엠에스바이오텍(주)\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"11\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000416991\",\n"
		+ "        \"prdlst_nm\": \"슈프리우먼V프로바이오틱스(SUPRE WOMEN V PROBIOTICS)\",\n"
		+ "        \"prms_dt\": \"20221014\",\n"
		+ "        \"prdlst_report_no\": \"200400200201063\",\n"
		+ "        \"bssh_nm\": \"엠에스바이오텍(주)\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"12\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000417192\",\n"
		+ "        \"prdlst_nm\": \"스마트 밸런스 큐\",\n"
		+ "        \"prms_dt\": \"20221014\",\n"
		+ "        \"prdlst_report_no\": \"200600200032549\",\n"
		+ "        \"bssh_nm\": \"콜마비앤에이치(주)음성공장\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"13\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000417188\",\n"
		+ "        \"prdlst_nm\": \"스타트윈\",\n"
		+ "        \"prms_dt\": \"20221014\",\n"
		+ "        \"prdlst_report_no\": \"200400200061795\",\n"
		+ "        \"bssh_nm\": \"(주)서흥\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"14\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000416996\",\n"
		+ "        \"prdlst_nm\": \"인큐텐 아이루트\",\n"
		+ "        \"prms_dt\": \"20221014\",\n"
		+ "        \"prdlst_report_no\": \"200400200023262\",\n"
		+ "        \"bssh_nm\": \"코스맥스바이오(주)\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"15\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000417190\",\n"
		+ "        \"prdlst_nm\": \"장수환 (將帥換)\",\n"
		+ "        \"prms_dt\": \"20221014\",\n"
		+ "        \"prdlst_report_no\": \"20130020008394\",\n"
		+ "        \"bssh_nm\": \"(주)오투바이오\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"16\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000414029\",\n"
		+ "        \"prdlst_nm\": \"비오텐슘 필업 플러스\",\n"
		+ "        \"prms_dt\": \"20221013\",\n"
		+ "        \"prdlst_report_no\": \"200400170061549\",\n"
		+ "        \"bssh_nm\": \"(주)알피바이오\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"17\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000415458\",\n"
		+ "        \"prdlst_nm\": \"고려태극인삼정 캡슐 슈퍼플래티늄\",\n"
		+ "        \"prms_dt\": \"20221013\",\n"
		+ "        \"prdlst_report_no\": \"2004002006224\",\n"
		+ "        \"bssh_nm\": \"주식회사 유림고려홍삼\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"18\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000415465\",\n"
		+ "        \"prdlst_nm\": \"KU홍삼眞 홍삼로얄\",\n"
		+ "        \"prms_dt\": \"20221013\",\n"
		+ "        \"prdlst_report_no\": \"20040020031428\",\n"
		+ "        \"bssh_nm\": \"대동고려삼(주)\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"19\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"prdlst_report_ledg_no\": \"2022021000415460\",\n"
		+ "        \"prdlst_nm\": \"4년근인삼농축액18\",\n"
		+ "        \"prms_dt\": \"20221013\",\n"
		+ "        \"prdlst_report_no\": \"20040020031427\",\n"
		+ "        \"bssh_nm\": \"대동고려삼(주)\",\n"
		+ "        \"total_count\": \"31874\",\n"
		+ "        \"no\": \"20\"\n"
		+ "    }\n"
		+ "]"),
	INGREDIENTS_JSON("[\n"
		+ "    {\n"
		+ "        \"rawmtrl_seq\": \"1\",\n"
		+ "        \"rawmtrl_nm\": \"테아닌\",\n"
		+ "        \"rawmtrl_dvs_cd\": \"011\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"rawmtrl_seq\": \"2\",\n"
		+ "        \"rawmtrl_nm\": \"비타민 B6\",\n"
		+ "        \"rawmtrl_dvs_cd\": \"011\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"rawmtrl_seq\": \"3\",\n"
		+ "        \"rawmtrl_nm\": \"유단백가수분해물\",\n"
		+ "        \"rawmtrl_dvs_cd\": \"011\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"rawmtrl_seq\": \"1\",\n"
		+ "        \"rawmtrl_nm\": \"L-테아닌\",\n"
		+ "        \"rawmtrl_dvs_cd\": \"021\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"rawmtrl_seq\": \"2\",\n"
		+ "        \"rawmtrl_nm\": \"비타민 B6\",\n"
		+ "        \"rawmtrl_dvs_cd\": \"021\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"rawmtrl_seq\": \"1\",\n"
		+ "        \"rawmtrl_nm\": \"유단백가수분해물\",\n"
		+ "        \"rawmtrl_dvs_cd\": \"023\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"rawmtrl_seq\": \"1\",\n"
		+ "        \"rawmtrl_nm\": \"마그네슘\",\n"
		+ "        \"rawmtrl_dvs_cd\": \"031\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"rawmtrl_seq\": \"2\",\n"
		+ "        \"rawmtrl_nm\": \"기타엿\",\n"
		+ "        \"rawmtrl_dvs_cd\": \"031\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"rawmtrl_seq\": \"3\",\n"
		+ "        \"rawmtrl_nm\": \"비타민 C\",\n"
		+ "        \"rawmtrl_dvs_cd\": \"031\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"rawmtrl_seq\": \"4\",\n"
		+ "        \"rawmtrl_nm\": \"산화아연\",\n"
		+ "        \"rawmtrl_dvs_cd\": \"031\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"rawmtrl_seq\": \"5\",\n"
		+ "        \"rawmtrl_nm\": \"혼합유당\",\n"
		+ "        \"rawmtrl_dvs_cd\": \"031\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"rawmtrl_seq\": \"6\",\n"
		+ "        \"rawmtrl_nm\": \"스테아린산마그네슘\",\n"
		+ "        \"rawmtrl_dvs_cd\": \"031\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"rawmtrl_seq\": \"7\",\n"
		+ "        \"rawmtrl_nm\": \"히드록시프로필메틸셀룰로스\",\n"
		+ "        \"rawmtrl_dvs_cd\": \"031\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"rawmtrl_seq\": \"8\",\n"
		+ "        \"rawmtrl_nm\": \"이산화규소\",\n"
		+ "        \"rawmtrl_dvs_cd\": \"031\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"rawmtrl_seq\": \"9\",\n"
		+ "        \"rawmtrl_nm\": \"글리세린지방산에스테르혼합제제용액\",\n"
		+ "        \"rawmtrl_dvs_cd\": \"031\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"rawmtrl_seq\": \"10\",\n"
		+ "        \"rawmtrl_nm\": \"카복시메틸셀룰로스칼슘\",\n"
		+ "        \"rawmtrl_dvs_cd\": \"031\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"rawmtrl_seq\": \"11\",\n"
		+ "        \"rawmtrl_nm\": \"칼슘\",\n"
		+ "        \"rawmtrl_dvs_cd\": \"031\"\n"
		+ "    },\n"
		+ "    {\n"
		+ "        \"rawmtrl_seq\": \"12\",\n"
		+ "        \"rawmtrl_nm\": \"L-트립토판\",\n"
		+ "        \"rawmtrl_dvs_cd\": \"031\"\n"
		+ "    }\n"
		+ "]");

	private final String data;

	SampleData(String data) {
		this.data = data;
	}

	public String getData() {
		return data;
	}
}
